from setuptools import setup, find_packages

setup(
    name='animeapi-py',
    version='0.0.1',
    description='A Python wrapper for the AnimeAPI by nattadasu with type hints and additional async support',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/Anime-API/animeapi-py',
    author='nattadasu',
    author_email='hello@nattadasu.my.id',
    license='AGPL-3.0',
    packages=find_packages(),
    install_requires=['aiohttp', 'requests', 'dacite'],
    python_requires='>=3.6',
    package_dir={'animeapi': 'animeapi'},
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Typing :: Typed',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3 :: Only',
        'Topic :: Internet :: WWW/HTTP :: Dynamic Content :: API',
        'Topic :: Software Development :: Libraries',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'Topic :: Utilities',
        'Natural Language :: English',
        'Operating System :: OS Independent',
    ],
    keywords='anime api wrapper relation mappings',
    project_urls={
        "Bug Reports": "https://github.com/nattadasu/animeapi-py/issues",
        "Source": "https://github.com/nattadasu/animeapi-py",
    },
)